spring:
  application:
    name: trans-trader

  # Redis 配置
  redis:
    host: localhost
    port: 6379
    database: 1

  # MongoDB 配置
  data:
    mongodb:
      host: localhost
      port: 27017
      database: technical_analysis

  # 定时任务配置
  task:
    scheduling:
      pool:
        size: 10

server:
  port: 8080
